package pe.edu.unsch.entities;
// Generated 19-nov-2020 18:08:16 by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

/**
 * Categoria generated by hbm2java
 */
@Entity
@Table(name = "categoria", catalog = "marketplacebd_test", uniqueConstraints = @UniqueConstraint(columnNames = "nombre"))
public class Categoria implements java.io.Serializable {

	private Integer idcategoria;
	private String nombre;
	private String desrcipcion;
	private Integer nProductos;
	private Integer proVendidos;
	private Set<CategoriaSubcategoria> categoriaSubcategoriasForIdsubcategoria = new HashSet<CategoriaSubcategoria>(0);
	private Set<CategoriaProducto> categoriaProductos = new HashSet<CategoriaProducto>(0);
	private Set<CategoriaSubcategoria> categoriaSubcategoriasForIdcategoria = new HashSet<CategoriaSubcategoria>(0);

	public Categoria() {
	}

	public Categoria(String nombre) {
		this.nombre = nombre;
	}

	public Categoria(String nombre, String desrcipcion,
			Set<CategoriaSubcategoria> categoriaSubcategoriasForIdsubcategoria,
			Set<CategoriaProducto> categoriaProductos,
			Set<CategoriaSubcategoria> categoriaSubcategoriasForIdcategoria) {
		this.nombre = nombre;
		this.desrcipcion = desrcipcion;
		this.categoriaSubcategoriasForIdsubcategoria = categoriaSubcategoriasForIdsubcategoria;
		this.categoriaProductos = categoriaProductos;
		this.categoriaSubcategoriasForIdcategoria = categoriaSubcategoriasForIdcategoria;
	}

	/** Constructor para mostrar las categorias con productos **/
	public Categoria(Integer idcategoria, String nombre, String desrcipcion, Integer nProductos, Integer proVendidos) {
		this.idcategoria = idcategoria;
		this.nombre = nombre;
		this.desrcipcion = desrcipcion;
		this.nProductos = nProductos;
		this.proVendidos = proVendidos;
	}

	
	public Categoria(Integer idcategoria, String nombre, String desrcipcion) {
		super();
		this.idcategoria = idcategoria;
		this.nombre = nombre;
		this.desrcipcion = desrcipcion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idcategoria", unique = true, nullable = false)
	public Integer getIdcategoria() {
		return this.idcategoria;
	}

	public void setIdcategoria(Integer idcategoria) {
		this.idcategoria = idcategoria;
	}

	@Column(name = "nombre", unique = true, nullable = false, length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "desrcipcion")
	public String getDesrcipcion() {
		return this.desrcipcion;
	}

	public void setDesrcipcion(String desrcipcion) {
		this.desrcipcion = desrcipcion;
	}

	// set and get nProductos proVendidos
	
	@Transient
	public Integer getnProductos() {
		return nProductos;
	}

	public void setnProductos(Integer nProductos) {
		this.nProductos = nProductos;
	}

	@Transient
	public Integer getProVendidos() {
		return proVendidos;
	}

	public void setProVendidos(Integer proVendidos) {
		this.proVendidos = proVendidos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categoriaByIdsubcategoria")
	public Set<CategoriaSubcategoria> getCategoriaSubcategoriasForIdsubcategoria() {
		return this.categoriaSubcategoriasForIdsubcategoria;
	}

	public void setCategoriaSubcategoriasForIdsubcategoria(
			Set<CategoriaSubcategoria> categoriaSubcategoriasForIdsubcategoria) {
		this.categoriaSubcategoriasForIdsubcategoria = categoriaSubcategoriasForIdsubcategoria;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categoria")
	public Set<CategoriaProducto> getCategoriaProductos() {
		return this.categoriaProductos;
	}

	public void setCategoriaProductos(Set<CategoriaProducto> categoriaProductos) {
		this.categoriaProductos = categoriaProductos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categoriaByIdcategoria")
	public Set<CategoriaSubcategoria> getCategoriaSubcategoriasForIdcategoria() {
		return this.categoriaSubcategoriasForIdcategoria;
	}

	public void setCategoriaSubcategoriasForIdcategoria(
			Set<CategoriaSubcategoria> categoriaSubcategoriasForIdcategoria) {
		this.categoriaSubcategoriasForIdcategoria = categoriaSubcategoriasForIdcategoria;
	}

}
