package pe.edu.unsch.entities;
// Generated 8 Nov 2020, 01:58:22 by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CategoriaProducto generated by hbm2java
 */
@Entity
@Table(name = "categoria_producto", catalog = "marketplacebd_test")
public class CategoriaProducto implements java.io.Serializable {

	private Integer idcategoriaproducto;
	private Categoria categoria;
	private Producto producto;
	private Set<ProductoComplementario> productoComplementarios = new HashSet<ProductoComplementario>(0);
	private Set<SugerenciasCate> sugerenciasCates = new HashSet<SugerenciasCate>(0);

	public CategoriaProducto() {
	}

	public CategoriaProducto(Categoria categoria, Producto producto) {
		this.categoria = categoria;
		this.producto = producto;
	}

	public CategoriaProducto(Categoria categoria, Producto producto,
			Set<ProductoComplementario> productoComplementarios, Set<SugerenciasCate> sugerenciasCates) {
		this.categoria = categoria;
		this.producto = producto;
		this.productoComplementarios = productoComplementarios;
		this.sugerenciasCates = sugerenciasCates;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idcategoriaproducto", unique = true, nullable = false)
	public Integer getIdcategoriaproducto() {
		return this.idcategoriaproducto;
	}

	public void setIdcategoriaproducto(Integer idcategoriaproducto) {
		this.idcategoriaproducto = idcategoriaproducto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcategoria", nullable = false)
	public Categoria getCategoria() {
		return this.categoria;
	}

	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idproducto", nullable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categoriaProducto")
	public Set<ProductoComplementario> getProductoComplementarios() {
		return this.productoComplementarios;
	}

	public void setProductoComplementarios(Set<ProductoComplementario> productoComplementarios) {
		this.productoComplementarios = productoComplementarios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categoriaProducto")
	public Set<SugerenciasCate> getSugerenciasCates() {
		return this.sugerenciasCates;
	}

	public void setSugerenciasCates(Set<SugerenciasCate> sugerenciasCates) {
		this.sugerenciasCates = sugerenciasCates;
	}

}
