package pe.edu.unsch.entities;
// Generated 4 Nov 2020, 21:14:55 by Hibernate Tools 5.1.10.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * ComprobanteVenta generated by hbm2java
 */
@Entity
@Table(name = "comprobante_venta", catalog = "marketplacebd_test", uniqueConstraints = @UniqueConstraint(columnNames = "numero_ruc"))
public class ComprobanteVenta implements java.io.Serializable {

	private int idcomprobanteventa;
	private BoletaVenta boletaVenta;
	private Factura factura;
	private Date fecha;
	private BigDecimal igv;
	private BigDecimal subtotal;
	private String numeroRuc;
	private Set<Pedido> pedidos = new HashSet<Pedido>(0);

	public ComprobanteVenta() {
	}

	public ComprobanteVenta(int idcomprobanteventa, Date fecha, BigDecimal igv, BigDecimal subtotal, String numeroRuc) {
		this.idcomprobanteventa = idcomprobanteventa;
		this.fecha = fecha;
		this.igv = igv;
		this.subtotal = subtotal;
		this.numeroRuc = numeroRuc;
	}

	public ComprobanteVenta(int idcomprobanteventa, BoletaVenta boletaVenta, Factura factura, Date fecha,
			BigDecimal igv, BigDecimal subtotal, String numeroRuc, Set<Pedido> pedidos) {
		this.idcomprobanteventa = idcomprobanteventa;
		this.boletaVenta = boletaVenta;
		this.factura = factura;
		this.fecha = fecha;
		this.igv = igv;
		this.subtotal = subtotal;
		this.numeroRuc = numeroRuc;
		this.pedidos = pedidos;
	}

	@Id

	@Column(name = "idcomprobanteventa", unique = true, nullable = false)
	public int getIdcomprobanteventa() {
		return this.idcomprobanteventa;
	}

	public void setIdcomprobanteventa(int idcomprobanteventa) {
		this.idcomprobanteventa = idcomprobanteventa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idboletaventa")
	public BoletaVenta getBoletaVenta() {
		return this.boletaVenta;
	}

	public void setBoletaVenta(BoletaVenta boletaVenta) {
		this.boletaVenta = boletaVenta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idfactura")
	public Factura getFactura() {
		return this.factura;
	}

	public void setFactura(Factura factura) {
		this.factura = factura;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", nullable = false, length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "igv", nullable = false, precision = 4)
	public BigDecimal getIgv() {
		return this.igv;
	}

	public void setIgv(BigDecimal igv) {
		this.igv = igv;
	}

	@Column(name = "subtotal", nullable = false, precision = 4)
	public BigDecimal getSubtotal() {
		return this.subtotal;
	}

	public void setSubtotal(BigDecimal subtotal) {
		this.subtotal = subtotal;
	}

	@Column(name = "numero_ruc", unique = true, nullable = false, length = 11)
	public String getNumeroRuc() {
		return this.numeroRuc;
	}

	public void setNumeroRuc(String numeroRuc) {
		this.numeroRuc = numeroRuc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "comprobanteVenta")
	public Set<Pedido> getPedidos() {
		return this.pedidos;
	}

	public void setPedidos(Set<Pedido> pedidos) {
		this.pedidos = pedidos;
	}

}
