package pe.edu.unsch.entities;
// Generated 8 Nov 2020, 01:58:22 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ContraReembolso generated by hbm2java
 */
@Entity
@Table(name = "contra_reembolso", catalog = "marketplacebd_test")
public class ContraReembolso implements java.io.Serializable {

	private int idcontrareembolso;
	private Pago pago;
	private String nombre;
	private Integer numeroCuenta;

	public ContraReembolso() {
	}

	public ContraReembolso(int idcontrareembolso, Pago pago) {
		this.idcontrareembolso = idcontrareembolso;
		this.pago = pago;
	}

	public ContraReembolso(int idcontrareembolso, Pago pago, String nombre, Integer numeroCuenta) {
		this.idcontrareembolso = idcontrareembolso;
		this.pago = pago;
		this.nombre = nombre;
		this.numeroCuenta = numeroCuenta;
	}

	@Id

	@Column(name = "idcontrareembolso", unique = true, nullable = false)
	public int getIdcontrareembolso() {
		return this.idcontrareembolso;
	}

	public void setIdcontrareembolso(int idcontrareembolso) {
		this.idcontrareembolso = idcontrareembolso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idpago", nullable = false)
	public Pago getPago() {
		return this.pago;
	}

	public void setPago(Pago pago) {
		this.pago = pago;
	}

	@Column(name = "nombre", length = 20)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "numero_cuenta")
	public Integer getNumeroCuenta() {
		return this.numeroCuenta;
	}

	public void setNumeroCuenta(Integer numeroCuenta) {
		this.numeroCuenta = numeroCuenta;
	}

}
