package pe.edu.unsch.entities;
// Generated 4 Nov 2020, 21:14:55 by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Direccion generated by hbm2java
 */
@Entity
@Table(name = "direccion", catalog = "marketplacebd_test")
public class Direccion implements java.io.Serializable {

	private int iddireccion;
	private String direccion;
	private String ciudad;
	private String pais;
	private String distrito;
	private String codigoPostal;
	private String descripcion;
	private Set<PersonaDireccion> personaDireccions = new HashSet<PersonaDireccion>(0);

	public Direccion() {
	}

	public Direccion(int iddireccion, String direccion) {
		this.iddireccion = iddireccion;
		this.direccion = direccion;
	}

	public Direccion(int iddireccion, String direccion, String ciudad, String pais, String distrito,
			String codigoPostal, String descripcion, Set<PersonaDireccion> personaDireccions) {
		this.iddireccion = iddireccion;
		this.direccion = direccion;
		this.ciudad = ciudad;
		this.pais = pais;
		this.distrito = distrito;
		this.codigoPostal = codigoPostal;
		this.descripcion = descripcion;
		this.personaDireccions = personaDireccions;
	}

	@Id

	@Column(name = "iddireccion", unique = true, nullable = false)
	public int getIddireccion() {
		return this.iddireccion;
	}

	public void setIddireccion(int iddireccion) {
		this.iddireccion = iddireccion;
	}

	@Column(name = "direccion", nullable = false, length = 45)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "ciudad", length = 45)
	public String getCiudad() {
		return this.ciudad;
	}

	public void setCiudad(String ciudad) {
		this.ciudad = ciudad;
	}

	@Column(name = "pais", length = 45)
	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	@Column(name = "distrito", length = 45)
	public String getDistrito() {
		return this.distrito;
	}

	public void setDistrito(String distrito) {
		this.distrito = distrito;
	}

	@Column(name = "codigo_postal", length = 45)
	public String getCodigoPostal() {
		return this.codigoPostal;
	}

	public void setCodigoPostal(String codigoPostal) {
		this.codigoPostal = codigoPostal;
	}

	@Column(name = "descripcion", length = 45)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "direccion")
	public Set<PersonaDireccion> getPersonaDireccions() {
		return this.personaDireccions;
	}

	public void setPersonaDireccions(Set<PersonaDireccion> personaDireccions) {
		this.personaDireccions = personaDireccions;
	}

}
