package pe.edu.unsch.entities;
// Generated 19-nov-2020 18:08:16 by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Factura generated by hbm2java
 */
@Entity
@Table(name = "factura", catalog = "marketplacebd_test")
public class Factura implements java.io.Serializable {

	private int idfactura;
	private Set<ComprobanteVenta> comprobanteVentas = new HashSet<ComprobanteVenta>(0);

	public Factura() {
	}

	public Factura(int idfactura) {
		this.idfactura = idfactura;
	}

	public Factura(int idfactura, Set<ComprobanteVenta> comprobanteVentas) {
		this.idfactura = idfactura;
		this.comprobanteVentas = comprobanteVentas;
	}

	@Id

	@Column(name = "idfactura", unique = true, nullable = false)
	public int getIdfactura() {
		return this.idfactura;
	}

	public void setIdfactura(int idfactura) {
		this.idfactura = idfactura;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "factura")
	public Set<ComprobanteVenta> getComprobanteVentas() {
		return this.comprobanteVentas;
	}

	public void setComprobanteVentas(Set<ComprobanteVenta> comprobanteVentas) {
		this.comprobanteVentas = comprobanteVentas;
	}

}
