package pe.edu.unsch.entities;
// Generated 8 Nov 2020, 01:58:22 by Hibernate Tools 5.1.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HistorialPedido generated by hbm2java
 */
@Entity
@Table(name = "historial_pedido", catalog = "marketplacebd_test")
public class HistorialPedido implements java.io.Serializable {

	private int idhistorialpedido;
	private Pedido pedido;
	private Producto producto;
	private Date fecha;

	public HistorialPedido() {
	}

	public HistorialPedido(int idhistorialpedido, Pedido pedido, Producto producto, Date fecha) {
		this.idhistorialpedido = idhistorialpedido;
		this.pedido = pedido;
		this.producto = producto;
		this.fecha = fecha;
	}

	@Id

	@Column(name = "idhistorialpedido", unique = true, nullable = false)
	public int getIdhistorialpedido() {
		return this.idhistorialpedido;
	}

	public void setIdhistorialpedido(int idhistorialpedido) {
		this.idhistorialpedido = idhistorialpedido;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idpedido", nullable = false)
	public Pedido getPedido() {
		return this.pedido;
	}

	public void setPedido(Pedido pedido) {
		this.pedido = pedido;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idproducto", nullable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", nullable = false, length = 19)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

}
