package pe.edu.unsch.entities;
// Generated 8 Nov 2020, 01:58:22 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ImagenProducto generated by hbm2java
 */
@Entity
@Table(name = "imagen_producto", catalog = "marketplacebd_test")
public class ImagenProducto implements java.io.Serializable {

	private Integer idimagenproducto;
	private Producto producto;
	private String direccion;

	public ImagenProducto() {
	}

	public ImagenProducto(Producto producto) {
		this.producto = producto;
	}

	public ImagenProducto(Producto producto, String direccion) {
		this.producto = producto;
		this.direccion = direccion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idimagenproducto", unique = true, nullable = false)
	public Integer getIdimagenproducto() {
		return this.idimagenproducto;
	}

	public void setIdimagenproducto(Integer idimagenproducto) {
		this.idimagenproducto = idimagenproducto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idproducto", nullable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@Column(name = "direccion", length = 586)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

}
