package pe.edu.unsch.entities;
// Generated 4 Nov 2020, 21:14:55 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ImagenProducto generated by hbm2java
 */
@Entity
@Table(name = "imagen_producto", catalog = "marketplacebd_test")
public class ImagenProducto implements java.io.Serializable {

	private int idimagenproducto;
	private Producto producto;
	private String direccion;

	public ImagenProducto() {
	}

	public ImagenProducto(int idimagenproducto, Producto producto) {
		this.idimagenproducto = idimagenproducto;
		this.producto = producto;
	}

	public ImagenProducto(int idimagenproducto, Producto producto, String direccion) {
		this.idimagenproducto = idimagenproducto;
		this.producto = producto;
		this.direccion = direccion;
	}

	@Id

	@Column(name = "idimagenproducto", unique = true, nullable = false)
	public int getIdimagenproducto() {
		return this.idimagenproducto;
	}

	public void setIdimagenproducto(int idimagenproducto) {
		this.idimagenproducto = idimagenproducto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idproducto", nullable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@Column(name = "direccion", length = 586)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

}
