package pe.edu.unsch.entities;
// Generated 19-nov-2020 18:08:16 by Hibernate Tools 5.1.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InfoVendedor generated by hbm2java
 */
@Entity
@Table(name = "info_vendedor", catalog = "marketplacebd_test")
public class InfoVendedor implements java.io.Serializable {

	private int idinfovendedor;
	private Rol rol;
	private Date tiempoderegistro;
	private int cantidadproductosvendidos;
	private int calificaciondevendedor;
	private String nombrevendedor;
	private String apellidovendedor;
	private String telefonovendedor;
	private String correovendedor;

	public InfoVendedor() {
	}

	public InfoVendedor(int idinfovendedor, Rol rol, Date tiempoderegistro, int cantidadproductosvendidos,
			int calificaciondevendedor, String nombrevendedor, String apellidovendedor, String telefonovendedor,
			String correovendedor) {
		this.idinfovendedor = idinfovendedor;
		this.rol = rol;
		this.tiempoderegistro = tiempoderegistro;
		this.cantidadproductosvendidos = cantidadproductosvendidos;
		this.calificaciondevendedor = calificaciondevendedor;
		this.nombrevendedor = nombrevendedor;
		this.apellidovendedor = apellidovendedor;
		this.telefonovendedor = telefonovendedor;
		this.correovendedor = correovendedor;
	}

	@Id

	@Column(name = "idinfovendedor", unique = true, nullable = false)
	public int getIdinfovendedor() {
		return this.idinfovendedor;
	}

	public void setIdinfovendedor(int idinfovendedor) {
		this.idinfovendedor = idinfovendedor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idrol", nullable = false)
	public Rol getRol() {
		return this.rol;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "tiempoderegistro", nullable = false, length = 10)
	public Date getTiempoderegistro() {
		return this.tiempoderegistro;
	}

	public void setTiempoderegistro(Date tiempoderegistro) {
		this.tiempoderegistro = tiempoderegistro;
	}

	@Column(name = "cantidadproductosvendidos", nullable = false)
	public int getCantidadproductosvendidos() {
		return this.cantidadproductosvendidos;
	}

	public void setCantidadproductosvendidos(int cantidadproductosvendidos) {
		this.cantidadproductosvendidos = cantidadproductosvendidos;
	}

	@Column(name = "calificaciondevendedor", nullable = false)
	public int getCalificaciondevendedor() {
		return this.calificaciondevendedor;
	}

	public void setCalificaciondevendedor(int calificaciondevendedor) {
		this.calificaciondevendedor = calificaciondevendedor;
	}

	@Column(name = "nombrevendedor", nullable = false, length = 45)
	public String getNombrevendedor() {
		return this.nombrevendedor;
	}

	public void setNombrevendedor(String nombrevendedor) {
		this.nombrevendedor = nombrevendedor;
	}

	@Column(name = "apellidovendedor", nullable = false, length = 45)
	public String getApellidovendedor() {
		return this.apellidovendedor;
	}

	public void setApellidovendedor(String apellidovendedor) {
		this.apellidovendedor = apellidovendedor;
	}

	@Column(name = "telefonovendedor", nullable = false, length = 9)
	public String getTelefonovendedor() {
		return this.telefonovendedor;
	}

	public void setTelefonovendedor(String telefonovendedor) {
		this.telefonovendedor = telefonovendedor;
	}

	@Column(name = "correovendedor", nullable = false, length = 45)
	public String getCorreovendedor() {
		return this.correovendedor;
	}

	public void setCorreovendedor(String correovendedor) {
		this.correovendedor = correovendedor;
	}

}
