package pe.edu.unsch.entities;
// Generated 19-nov-2020 18:08:16 by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Modulo generated by hbm2java
 */
@Entity
@Table(name = "modulo", catalog = "marketplacebd_test", uniqueConstraints = { @UniqueConstraint(columnNames = "icono"),
		@UniqueConstraint(columnNames = "nombre") })
public class Modulo implements java.io.Serializable {

	private int idmodulo;
	private String nombre;
	private String icono;
	private Set<SubModulo> subModulos = new HashSet<SubModulo>(0);

	public Modulo() {
	}

	public Modulo(int idmodulo, String nombre, String icono) {
		this.idmodulo = idmodulo;
		this.nombre = nombre;
		this.icono = icono;
	}

	public Modulo(int idmodulo, String nombre, String icono, Set<SubModulo> subModulos) {
		this.idmodulo = idmodulo;
		this.nombre = nombre;
		this.icono = icono;
		this.subModulos = subModulos;
	}

	@Id

	@Column(name = "idmodulo", unique = true, nullable = false)
	public int getIdmodulo() {
		return this.idmodulo;
	}

	public void setIdmodulo(int idmodulo) {
		this.idmodulo = idmodulo;
	}

	@Column(name = "nombre", unique = true, nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "icono", unique = true, nullable = false, length = 45)
	public String getIcono() {
		return this.icono;
	}

	public void setIcono(String icono) {
		this.icono = icono;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modulo")
	public Set<SubModulo> getSubModulos() {
		return this.subModulos;
	}

	public void setSubModulos(Set<SubModulo> subModulos) {
		this.subModulos = subModulos;
	}

}
