package pe.edu.unsch.entities;
// Generated 4 Nov 2020, 21:14:55 by Hibernate Tools 5.1.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OfertaProducto generated by hbm2java
 */
@Entity
@Table(name = "oferta_producto", catalog = "marketplacebd_test")
public class OfertaProducto implements java.io.Serializable {

	private long idofertaproducto;
	private Producto producto;
	private String descripcion;
	private float precioOferta;
	private Date fechaInicio;
	private Date fechaLimite;
	private Date fechaCreacion;
	private boolean estado;
	private Integer valoracionProducto;

	public OfertaProducto() {
	}

	public OfertaProducto(long idofertaproducto, Producto producto, String descripcion, float precioOferta,
			Date fechaInicio, Date fechaLimite, Date fechaCreacion, boolean estado) {
		this.idofertaproducto = idofertaproducto;
		this.producto = producto;
		this.descripcion = descripcion;
		this.precioOferta = precioOferta;
		this.fechaInicio = fechaInicio;
		this.fechaLimite = fechaLimite;
		this.fechaCreacion = fechaCreacion;
		this.estado = estado;
	}

	public OfertaProducto(long idofertaproducto, Producto producto, String descripcion, float precioOferta,
			Date fechaInicio, Date fechaLimite, Date fechaCreacion, boolean estado, Integer valoracionProducto) {
		this.idofertaproducto = idofertaproducto;
		this.producto = producto;
		this.descripcion = descripcion;
		this.precioOferta = precioOferta;
		this.fechaInicio = fechaInicio;
		this.fechaLimite = fechaLimite;
		this.fechaCreacion = fechaCreacion;
		this.estado = estado;
		this.valoracionProducto = valoracionProducto;
	}

	@Id

	@Column(name = "idofertaproducto", unique = true, nullable = false)
	public long getIdofertaproducto() {
		return this.idofertaproducto;
	}

	public void setIdofertaproducto(long idofertaproducto) {
		this.idofertaproducto = idofertaproducto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idproducto", nullable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@Column(name = "descripcion", nullable = false, length = 65535)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "precio_oferta", nullable = false, precision = 12, scale = 0)
	public float getPrecioOferta() {
		return this.precioOferta;
	}

	public void setPrecioOferta(float precioOferta) {
		this.precioOferta = precioOferta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_inicio", nullable = false, length = 19)
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_limite", nullable = false, length = 19)
	public Date getFechaLimite() {
		return this.fechaLimite;
	}

	public void setFechaLimite(Date fechaLimite) {
		this.fechaLimite = fechaLimite;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_creacion", nullable = false, length = 19)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "estado", nullable = false)
	public boolean isEstado() {
		return this.estado;
	}

	public void setEstado(boolean estado) {
		this.estado = estado;
	}

	@Column(name = "valoracion_producto")
	public Integer getValoracionProducto() {
		return this.valoracionProducto;
	}

	public void setValoracionProducto(Integer valoracionProducto) {
		this.valoracionProducto = valoracionProducto;
	}

}
