package pe.edu.unsch.entities;
// Generated 19-nov-2020 18:08:16 by Hibernate Tools 5.1.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Pedido generated by hbm2java
 */
@Entity
@Table(name = "pedido", catalog = "marketplacebd_test", uniqueConstraints = @UniqueConstraint(columnNames = "codigo"))
public class Pedido implements java.io.Serializable {

	private long idpedido;
	private CompradorFrecuente compradorFrecuente;
	private ComprobanteVenta comprobanteVenta;
	private Pago pago;
	private SeguimientoPedido seguimientoPedido;
	private Usuario usuario;
	private String codigo;
	private Date fecha;
	private String direccionEntrega;
	private int cantidadProducto;
	private byte estadoPedido;
	private long precioProducto;
	private long descuentoProducto;
	private String pagoPendiente;
	private Set<HistorialPedido> historialPedidos = new HashSet<HistorialPedido>(0);
	private Set<Notificacion> notificacions = new HashSet<Notificacion>(0);

	public Pedido() {
	}

	public Pedido(long idpedido, CompradorFrecuente compradorFrecuente, SeguimientoPedido seguimientoPedido,
			Usuario usuario, String codigo, Date fecha, String direccionEntrega, int cantidadProducto,
			byte estadoPedido, long precioProducto, long descuentoProducto, String pagoPendiente) {
		this.idpedido = idpedido;
		this.compradorFrecuente = compradorFrecuente;
		this.seguimientoPedido = seguimientoPedido;
		this.usuario = usuario;
		this.codigo = codigo;
		this.fecha = fecha;
		this.direccionEntrega = direccionEntrega;
		this.cantidadProducto = cantidadProducto;
		this.estadoPedido = estadoPedido;
		this.precioProducto = precioProducto;
		this.descuentoProducto = descuentoProducto;
		this.pagoPendiente = pagoPendiente;
	}

	public Pedido(long idpedido, CompradorFrecuente compradorFrecuente, ComprobanteVenta comprobanteVenta, Pago pago,
			SeguimientoPedido seguimientoPedido, Usuario usuario, String codigo, Date fecha, String direccionEntrega,
			int cantidadProducto, byte estadoPedido, long precioProducto, long descuentoProducto, String pagoPendiente,
			Set<HistorialPedido> historialPedidos, Set<Notificacion> notificacions) {
		this.idpedido = idpedido;
		this.compradorFrecuente = compradorFrecuente;
		this.comprobanteVenta = comprobanteVenta;
		this.pago = pago;
		this.seguimientoPedido = seguimientoPedido;
		this.usuario = usuario;
		this.codigo = codigo;
		this.fecha = fecha;
		this.direccionEntrega = direccionEntrega;
		this.cantidadProducto = cantidadProducto;
		this.estadoPedido = estadoPedido;
		this.precioProducto = precioProducto;
		this.descuentoProducto = descuentoProducto;
		this.pagoPendiente = pagoPendiente;
		this.historialPedidos = historialPedidos;
		this.notificacions = notificacions;
	}

	@Id

	@Column(name = "idpedido", unique = true, nullable = false)
	public long getIdpedido() {
		return this.idpedido;
	}

	public void setIdpedido(long idpedido) {
		this.idpedido = idpedido;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcompradorfrecuente", nullable = false)
	public CompradorFrecuente getCompradorFrecuente() {
		return this.compradorFrecuente;
	}

	public void setCompradorFrecuente(CompradorFrecuente compradorFrecuente) {
		this.compradorFrecuente = compradorFrecuente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcomprobanteventa")
	public ComprobanteVenta getComprobanteVenta() {
		return this.comprobanteVenta;
	}

	public void setComprobanteVenta(ComprobanteVenta comprobanteVenta) {
		this.comprobanteVenta = comprobanteVenta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idpago")
	public Pago getPago() {
		return this.pago;
	}

	public void setPago(Pago pago) {
		this.pago = pago;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idseguimientopedido", nullable = false)
	public SeguimientoPedido getSeguimientoPedido() {
		return this.seguimientoPedido;
	}

	public void setSeguimientoPedido(SeguimientoPedido seguimientoPedido) {
		this.seguimientoPedido = seguimientoPedido;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idusuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "codigo", unique = true, nullable = false, length = 20)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", nullable = false, length = 19)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "direccion_entrega", nullable = false, length = 200)
	public String getDireccionEntrega() {
		return this.direccionEntrega;
	}

	public void setDireccionEntrega(String direccionEntrega) {
		this.direccionEntrega = direccionEntrega;
	}

	@Column(name = "cantidad_producto", nullable = false)
	public int getCantidadProducto() {
		return this.cantidadProducto;
	}

	public void setCantidadProducto(int cantidadProducto) {
		this.cantidadProducto = cantidadProducto;
	}

	@Column(name = "estado_pedido", nullable = false)
	public byte getEstadoPedido() {
		return this.estadoPedido;
	}

	public void setEstadoPedido(byte estadoPedido) {
		this.estadoPedido = estadoPedido;
	}

	@Column(name = "precio_producto", nullable = false, precision = 10, scale = 0)
	public long getPrecioProducto() {
		return this.precioProducto;
	}

	public void setPrecioProducto(long precioProducto) {
		this.precioProducto = precioProducto;
	}

	@Column(name = "descuento_producto", nullable = false, precision = 10, scale = 0)
	public long getDescuentoProducto() {
		return this.descuentoProducto;
	}

	public void setDescuentoProducto(long descuentoProducto) {
		this.descuentoProducto = descuentoProducto;
	}

	@Column(name = "pago_pendiente", nullable = false, length = 50)
	public String getPagoPendiente() {
		return this.pagoPendiente;
	}

	public void setPagoPendiente(String pagoPendiente) {
		this.pagoPendiente = pagoPendiente;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pedido")
	public Set<HistorialPedido> getHistorialPedidos() {
		return this.historialPedidos;
	}

	public void setHistorialPedidos(Set<HistorialPedido> historialPedidos) {
		this.historialPedidos = historialPedidos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pedido")
	public Set<Notificacion> getNotificacions() {
		return this.notificacions;
	}

	public void setNotificacions(Set<Notificacion> notificacions) {
		this.notificacions = notificacions;
	}

}
