package pe.edu.unsch.entities;
// Generated 4 Nov 2020, 21:14:55 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PersonaRol generated by hbm2java
 */
@Entity
@Table(name = "persona_rol", catalog = "marketplacebd_test")
public class PersonaRol implements java.io.Serializable {

	private int idpersonarol;
	private Persona persona;
	private Rol rol;
	private byte estado;

	public PersonaRol() {
	}

	public PersonaRol(int idpersonarol, Persona persona, Rol rol, byte estado) {
		this.idpersonarol = idpersonarol;
		this.persona = persona;
		this.rol = rol;
		this.estado = estado;
	}

	@Id

	@Column(name = "idpersonarol", unique = true, nullable = false)
	public int getIdpersonarol() {
		return this.idpersonarol;
	}

	public void setIdpersonarol(int idpersonarol) {
		this.idpersonarol = idpersonarol;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idpersona", nullable = false)
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idrol", nullable = false)
	public Rol getRol() {
		return this.rol;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}

	@Column(name = "estado", nullable = false)
	public byte getEstado() {
		return this.estado;
	}

	public void setEstado(byte estado) {
		this.estado = estado;
	}

}
