package pe.edu.unsch.entities;
// Generated 8 Nov 2020, 01:58:22 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Premio generated by hbm2java
 */
@Entity
@Table(name = "premio", catalog = "marketplacebd_test")
public class Premio implements java.io.Serializable {

	private int idpremio;
	private CompradorFrecuente compradorFrecuente;
	private String descripcionPremio;
	private String categoria;

	public Premio() {
	}

	public Premio(int idpremio, CompradorFrecuente compradorFrecuente) {
		this.idpremio = idpremio;
		this.compradorFrecuente = compradorFrecuente;
	}

	public Premio(int idpremio, CompradorFrecuente compradorFrecuente, String descripcionPremio, String categoria) {
		this.idpremio = idpremio;
		this.compradorFrecuente = compradorFrecuente;
		this.descripcionPremio = descripcionPremio;
		this.categoria = categoria;
	}

	@Id

	@Column(name = "idpremio", unique = true, nullable = false)
	public int getIdpremio() {
		return this.idpremio;
	}

	public void setIdpremio(int idpremio) {
		this.idpremio = idpremio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcompradorfrecuente", nullable = false)
	public CompradorFrecuente getCompradorFrecuente() {
		return this.compradorFrecuente;
	}

	public void setCompradorFrecuente(CompradorFrecuente compradorFrecuente) {
		this.compradorFrecuente = compradorFrecuente;
	}

	@Column(name = "descripcion_premio", length = 100)
	public String getDescripcionPremio() {
		return this.descripcionPremio;
	}

	public void setDescripcionPremio(String descripcionPremio) {
		this.descripcionPremio = descripcionPremio;
	}

	@Column(name = "categoria", length = 45)
	public String getCategoria() {
		return this.categoria;
	}

	public void setCategoria(String categoria) {
		this.categoria = categoria;
	}

}
