package pe.edu.unsch.entities;
// Generated 19-nov-2020 18:08:16 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProductoComplementario generated by hbm2java
 */
@Entity
@Table(name = "producto_complementario", catalog = "marketplacebd_test")
public class ProductoComplementario implements java.io.Serializable {

	private Integer idproductocomplementario;
	private CategoriaProducto categoriaProducto;
	private String categoria;

	public ProductoComplementario() {
	}

	public ProductoComplementario(CategoriaProducto categoriaProducto, String categoria) {
		this.categoriaProducto = categoriaProducto;
		this.categoria = categoria;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idproductocomplementario", unique = true, nullable = false)
	public Integer getIdproductocomplementario() {
		return this.idproductocomplementario;
	}

	public void setIdproductocomplementario(Integer idproductocomplementario) {
		this.idproductocomplementario = idproductocomplementario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcategoriaproducto", nullable = false)
	public CategoriaProducto getCategoriaProducto() {
		return this.categoriaProducto;
	}

	public void setCategoriaProducto(CategoriaProducto categoriaProducto) {
		this.categoriaProducto = categoriaProducto;
	}

	@Column(name = "categoria", nullable = false, length = 45)
	public String getCategoria() {
		return this.categoria;
	}

	public void setCategoria(String categoria) {
		this.categoria = categoria;
	}

}
