package pe.edu.unsch.entities;
// Generated 8 Nov 2020, 01:58:22 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProductoFavorito generated by hbm2java
 */
@Entity
@Table(name = "producto_favorito", catalog = "marketplacebd_test")
public class ProductoFavorito implements java.io.Serializable {

	private int idproductofavorito;
	private Persona persona;
	private Producto producto;

	public ProductoFavorito() {
	}

	public ProductoFavorito(int idproductofavorito, Persona persona, Producto producto) {
		this.idproductofavorito = idproductofavorito;
		this.persona = persona;
		this.producto = producto;
	}

	@Id

	@Column(name = "idproductofavorito", unique = true, nullable = false)
	public int getIdproductofavorito() {
		return this.idproductofavorito;
	}

	public void setIdproductofavorito(int idproductofavorito) {
		this.idproductofavorito = idproductofavorito;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idpersona", nullable = false)
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idproducto", nullable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

}
