package pe.edu.unsch.entities;
// Generated 19-nov-2020 18:08:16 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Productosjuntos generated by hbm2java
 */
@Entity
@Table(name = "productosjuntos", catalog = "marketplacebd_test")
public class Productosjuntos implements java.io.Serializable {

	private long idproductosjuntos;
	private Producto productoByProducto2;
	private Producto productoByProducto1;

	public Productosjuntos() {
	}

	public Productosjuntos(long idproductosjuntos, Producto productoByProducto2, Producto productoByProducto1) {
		this.idproductosjuntos = idproductosjuntos;
		this.productoByProducto2 = productoByProducto2;
		this.productoByProducto1 = productoByProducto1;
	}

	@Id

	@Column(name = "idproductosjuntos", unique = true, nullable = false)
	public long getIdproductosjuntos() {
		return this.idproductosjuntos;
	}

	public void setIdproductosjuntos(long idproductosjuntos) {
		this.idproductosjuntos = idproductosjuntos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "producto2", nullable = false)
	public Producto getProductoByProducto2() {
		return this.productoByProducto2;
	}

	public void setProductoByProducto2(Producto productoByProducto2) {
		this.productoByProducto2 = productoByProducto2;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "producto1", nullable = false)
	public Producto getProductoByProducto1() {
		return this.productoByProducto1;
	}

	public void setProductoByProducto1(Producto productoByProducto1) {
		this.productoByProducto1 = productoByProducto1;
	}

}
