package pe.edu.unsch.entities;
// Generated 19-nov-2020 18:08:16 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Regalo generated by hbm2java
 */
@Entity
@Table(name = "regalo", catalog = "marketplacebd_test")
public class Regalo implements java.io.Serializable {

	private Integer idregalo;
	private CompradorFrecuente compradorFrecuente;
	private String descripcionRegalo;
	private String categoria;
	private String puntosRequeridos;

	public Regalo() {
	}

	public Regalo(CompradorFrecuente compradorFrecuente, String descripcionRegalo, String categoria,
			String puntosRequeridos) {
		this.compradorFrecuente = compradorFrecuente;
		this.descripcionRegalo = descripcionRegalo;
		this.categoria = categoria;
		this.puntosRequeridos = puntosRequeridos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idregalo", unique = true, nullable = false)
	public Integer getIdregalo() {
		return this.idregalo;
	}

	public void setIdregalo(Integer idregalo) {
		this.idregalo = idregalo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcompradorfrecuente", nullable = false)
	public CompradorFrecuente getCompradorFrecuente() {
		return this.compradorFrecuente;
	}

	public void setCompradorFrecuente(CompradorFrecuente compradorFrecuente) {
		this.compradorFrecuente = compradorFrecuente;
	}

	@Column(name = "descripcion_regalo", nullable = false, length = 100)
	public String getDescripcionRegalo() {
		return this.descripcionRegalo;
	}

	public void setDescripcionRegalo(String descripcionRegalo) {
		this.descripcionRegalo = descripcionRegalo;
	}

	@Column(name = "categoria", nullable = false, length = 45)
	public String getCategoria() {
		return this.categoria;
	}

	public void setCategoria(String categoria) {
		this.categoria = categoria;
	}

	@Column(name = "puntos_requeridos", nullable = false, length = 45)
	public String getPuntosRequeridos() {
		return this.puntosRequeridos;
	}

	public void setPuntosRequeridos(String puntosRequeridos) {
		this.puntosRequeridos = puntosRequeridos;
	}

}
