package pe.edu.unsch.entities;
// Generated 19-nov-2020 18:08:16 by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Rol generated by hbm2java
 */
@Entity
@Table(name = "rol", catalog = "marketplacebd_test", uniqueConstraints = @UniqueConstraint(columnNames = "nombre"))
public class Rol implements java.io.Serializable {

	private int idrol;
	private String nombre;
	private Set<InfoVendedor> infoVendedors = new HashSet<InfoVendedor>(0);
	private Set<RolUsuario> rolUsuarios = new HashSet<RolUsuario>(0);
	private Set<RolOpcion> rolOpcions = new HashSet<RolOpcion>(0);

	public Rol() {
	}

	public Rol(int idrol, String nombre) {
		this.idrol = idrol;
		this.nombre = nombre;
	}

	public Rol(int idrol, String nombre, Set<InfoVendedor> infoVendedors, Set<RolUsuario> rolUsuarios,
			Set<RolOpcion> rolOpcions) {
		this.idrol = idrol;
		this.nombre = nombre;
		this.infoVendedors = infoVendedors;
		this.rolUsuarios = rolUsuarios;
		this.rolOpcions = rolOpcions;
	}

	@Id

	@Column(name = "idrol", unique = true, nullable = false)
	public int getIdrol() {
		return this.idrol;
	}

	public void setIdrol(int idrol) {
		this.idrol = idrol;
	}

	@Column(name = "nombre", unique = true, nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rol")
	public Set<InfoVendedor> getInfoVendedors() {
		return this.infoVendedors;
	}

	public void setInfoVendedors(Set<InfoVendedor> infoVendedors) {
		this.infoVendedors = infoVendedors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rol")
	public Set<RolUsuario> getRolUsuarios() {
		return this.rolUsuarios;
	}

	public void setRolUsuarios(Set<RolUsuario> rolUsuarios) {
		this.rolUsuarios = rolUsuarios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rol")
	public Set<RolOpcion> getRolOpcions() {
		return this.rolOpcions;
	}

	public void setRolOpcions(Set<RolOpcion> rolOpcions) {
		this.rolOpcions = rolOpcions;
	}

}
