package pe.edu.unsch.entities;
// Generated 19-nov-2020 18:08:16 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RolOpcion generated by hbm2java
 */
@Entity
@Table(name = "rol_opcion", catalog = "marketplacebd_test")
public class RolOpcion implements java.io.Serializable {

	private int idrolopcion;
	private Opcion opcion;
	private Rol rol;

	public RolOpcion() {
	}

	public RolOpcion(int idrolopcion, Opcion opcion, Rol rol) {
		this.idrolopcion = idrolopcion;
		this.opcion = opcion;
		this.rol = rol;
	}

	@Id

	@Column(name = "idrolopcion", unique = true, nullable = false)
	public int getIdrolopcion() {
		return this.idrolopcion;
	}

	public void setIdrolopcion(int idrolopcion) {
		this.idrolopcion = idrolopcion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idopcion", nullable = false)
	public Opcion getOpcion() {
		return this.opcion;
	}

	public void setOpcion(Opcion opcion) {
		this.opcion = opcion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idrol", nullable = false)
	public Rol getRol() {
		return this.rol;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}

}
