package pe.edu.unsch.entities;
// Generated 8 Nov 2020, 01:58:22 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RolUsuario generated by hbm2java
 */
@Entity
@Table(name = "rol_usuario", catalog = "marketplacebd_test")
public class RolUsuario implements java.io.Serializable {

	private int idrolusuario;
	private Rol rol;
	private Usuario usuario;
	private byte estado;

	public RolUsuario() {
	}

	public RolUsuario(int idrolusuario, Rol rol, Usuario usuario, byte estado) {
		this.idrolusuario = idrolusuario;
		this.rol = rol;
		this.usuario = usuario;
		this.estado = estado;
	}

	@Id

	@Column(name = "idrolusuario", unique = true, nullable = false)
	public int getIdrolusuario() {
		return this.idrolusuario;
	}

	public void setIdrolusuario(int idrolusuario) {
		this.idrolusuario = idrolusuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idrol", nullable = false)
	public Rol getRol() {
		return this.rol;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idusuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "estado", nullable = false)
	public byte getEstado() {
		return this.estado;
	}

	public void setEstado(byte estado) {
		this.estado = estado;
	}

}
