package pe.edu.unsch.entities;
// Generated 19-nov-2020 18:08:16 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RolUsuario generated by hbm2java
 */
@Entity
@Table(name = "rol_usuario", catalog = "marketplacebd_test")
public class RolUsuario implements java.io.Serializable {

	private Integer idrolusuario;
	private Rol rol;
	private Usuario usuario;
	private byte estado;

	public RolUsuario() {
	}

	public RolUsuario(Rol rol, Usuario usuario, byte estado) {
		this.rol = rol;
		this.usuario = usuario;
		this.estado = estado;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idrolusuario", unique = true, nullable = false)
	public Integer getIdrolusuario() {
		return this.idrolusuario;
	}

	public void setIdrolusuario(Integer idrolusuario) {
		this.idrolusuario = idrolusuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idrol", nullable = false)
	public Rol getRol() {
		return this.rol;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idusuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "estado", nullable = false)
	public byte getEstado() {
		return this.estado;
	}

	public void setEstado(byte estado) {
		this.estado = estado;
	}

}
