package pe.edu.unsch.entities;
// Generated 19-nov-2020 18:08:16 by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SeguimientoPedido generated by hbm2java
 */
@Entity
@Table(name = "seguimiento_pedido", catalog = "marketplacebd_test")
public class SeguimientoPedido implements java.io.Serializable {

	private Integer idseguimientopedido;
	private String tiposeguimiento;
	private String estado;
	private Set<Pedido> pedidos = new HashSet<Pedido>(0);

	public SeguimientoPedido() {
	}

	public SeguimientoPedido(String tiposeguimiento) {
		this.tiposeguimiento = tiposeguimiento;
	}

	public SeguimientoPedido(String tiposeguimiento, String estado, Set<Pedido> pedidos) {
		this.tiposeguimiento = tiposeguimiento;
		this.estado = estado;
		this.pedidos = pedidos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idseguimientopedido", unique = true, nullable = false)
	public Integer getIdseguimientopedido() {
		return this.idseguimientopedido;
	}

	public void setIdseguimientopedido(Integer idseguimientopedido) {
		this.idseguimientopedido = idseguimientopedido;
	}

	@Column(name = "tiposeguimiento", nullable = false, length = 30)
	public String getTiposeguimiento() {
		return this.tiposeguimiento;
	}

	public void setTiposeguimiento(String tiposeguimiento) {
		this.tiposeguimiento = tiposeguimiento;
	}

	@Column(name = "estado", length = 45)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "seguimientoPedido")
	public Set<Pedido> getPedidos() {
		return this.pedidos;
	}

	public void setPedidos(Set<Pedido> pedidos) {
		this.pedidos = pedidos;
	}

}
