package pe.edu.unsch.entities;
// Generated 19-nov-2020 18:08:16 by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * SubModulo generated by hbm2java
 */
@Entity
@Table(name = "sub_modulo", catalog = "marketplacebd_test", uniqueConstraints = {
		@UniqueConstraint(columnNames = "estado"), @UniqueConstraint(columnNames = "nombre") })
public class SubModulo implements java.io.Serializable {

	private int idsubmodulo;
	private Modulo modulo;
	private String nombre;
	private byte estado;
	private Set<Opcion> opcions = new HashSet<Opcion>(0);

	public SubModulo() {
	}

	public SubModulo(int idsubmodulo, Modulo modulo, String nombre, byte estado) {
		this.idsubmodulo = idsubmodulo;
		this.modulo = modulo;
		this.nombre = nombre;
		this.estado = estado;
	}

	public SubModulo(int idsubmodulo, Modulo modulo, String nombre, byte estado, Set<Opcion> opcions) {
		this.idsubmodulo = idsubmodulo;
		this.modulo = modulo;
		this.nombre = nombre;
		this.estado = estado;
		this.opcions = opcions;
	}

	@Id

	@Column(name = "idsubmodulo", unique = true, nullable = false)
	public int getIdsubmodulo() {
		return this.idsubmodulo;
	}

	public void setIdsubmodulo(int idsubmodulo) {
		this.idsubmodulo = idsubmodulo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idmodulo", nullable = false)
	public Modulo getModulo() {
		return this.modulo;
	}

	public void setModulo(Modulo modulo) {
		this.modulo = modulo;
	}

	@Column(name = "nombre", unique = true, nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "estado", unique = true, nullable = false)
	public byte getEstado() {
		return this.estado;
	}

	public void setEstado(byte estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subModulo")
	public Set<Opcion> getOpcions() {
		return this.opcions;
	}

	public void setOpcions(Set<Opcion> opcions) {
		this.opcions = opcions;
	}

}
