package pe.edu.unsch.entities;
// Generated 19-nov-2020 18:08:16 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SugerenciasCate generated by hbm2java
 */
@Entity
@Table(name = "sugerencias_cate", catalog = "marketplacebd_test")
public class SugerenciasCate implements java.io.Serializable {

	private int idsugerencias;
	private CategoriaProducto categoriaProducto;
	private String descripcion;

	public SugerenciasCate() {
	}

	public SugerenciasCate(int idsugerencias, CategoriaProducto categoriaProducto, String descripcion) {
		this.idsugerencias = idsugerencias;
		this.categoriaProducto = categoriaProducto;
		this.descripcion = descripcion;
	}

	@Id

	@Column(name = "idsugerencias", unique = true, nullable = false)
	public int getIdsugerencias() {
		return this.idsugerencias;
	}

	public void setIdsugerencias(int idsugerencias) {
		this.idsugerencias = idsugerencias;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcategoriaproducto", nullable = false)
	public CategoriaProducto getCategoriaProducto() {
		return this.categoriaProducto;
	}

	public void setCategoriaProducto(CategoriaProducto categoriaProducto) {
		this.categoriaProducto = categoriaProducto;
	}

	@Column(name = "descripcion", nullable = false, length = 80)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
