package pe.edu.unsch.entities;
// Generated 4 Nov 2020, 21:14:55 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Sugerenciahistorial generated by hbm2java
 */
@Entity
@Table(name = "sugerenciahistorial", catalog = "marketplacebd_test")
public class Sugerenciahistorial implements java.io.Serializable {

	private int idsugerenciahistorial;
	private Producto producto;
	private String historial;
	private String descripcion;

	public Sugerenciahistorial() {
	}

	public Sugerenciahistorial(int idsugerenciahistorial, Producto producto, String historial, String descripcion) {
		this.idsugerenciahistorial = idsugerenciahistorial;
		this.producto = producto;
		this.historial = historial;
		this.descripcion = descripcion;
	}

	@Id

	@Column(name = "idsugerenciahistorial", unique = true, nullable = false)
	public int getIdsugerenciahistorial() {
		return this.idsugerenciahistorial;
	}

	public void setIdsugerenciahistorial(int idsugerenciahistorial) {
		this.idsugerenciahistorial = idsugerenciahistorial;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idproducto", nullable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@Column(name = "historial", nullable = false, length = 45)
	public String getHistorial() {
		return this.historial;
	}

	public void setHistorial(String historial) {
		this.historial = historial;
	}

	@Column(name = "descripcion", nullable = false, length = 80)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
