package pe.edu.unsch.entities;
// Generated 4 Nov 2020, 21:14:55 by Hibernate Tools 5.1.10.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Tarjeta generated by hbm2java
 */
@Entity
@Table(name = "tarjeta", catalog = "marketplacebd_test", uniqueConstraints = {
		@UniqueConstraint(columnNames = "cod_verificacion_tarjeta"),
		@UniqueConstraint(columnNames = "numero_tarjeta") })
public class Tarjeta implements java.io.Serializable {

	private int idtarjeta;
	private String numeroTarjeta;
	private String codVerificacionTarjeta;
	private Date fechaDeposito;
	private BigDecimal montoDeposito;
	private Date fechaVencimiento;
	private String nombre;
	private Set<Pago> pagos = new HashSet<Pago>(0);

	public Tarjeta() {
	}

	public Tarjeta(int idtarjeta, String numeroTarjeta, String codVerificacionTarjeta, Date fechaDeposito,
			BigDecimal montoDeposito, Date fechaVencimiento) {
		this.idtarjeta = idtarjeta;
		this.numeroTarjeta = numeroTarjeta;
		this.codVerificacionTarjeta = codVerificacionTarjeta;
		this.fechaDeposito = fechaDeposito;
		this.montoDeposito = montoDeposito;
		this.fechaVencimiento = fechaVencimiento;
	}

	public Tarjeta(int idtarjeta, String numeroTarjeta, String codVerificacionTarjeta, Date fechaDeposito,
			BigDecimal montoDeposito, Date fechaVencimiento, String nombre, Set<Pago> pagos) {
		this.idtarjeta = idtarjeta;
		this.numeroTarjeta = numeroTarjeta;
		this.codVerificacionTarjeta = codVerificacionTarjeta;
		this.fechaDeposito = fechaDeposito;
		this.montoDeposito = montoDeposito;
		this.fechaVencimiento = fechaVencimiento;
		this.nombre = nombre;
		this.pagos = pagos;
	}

	@Id

	@Column(name = "idtarjeta", unique = true, nullable = false)
	public int getIdtarjeta() {
		return this.idtarjeta;
	}

	public void setIdtarjeta(int idtarjeta) {
		this.idtarjeta = idtarjeta;
	}

	@Column(name = "numero_tarjeta", unique = true, nullable = false, length = 16)
	public String getNumeroTarjeta() {
		return this.numeroTarjeta;
	}

	public void setNumeroTarjeta(String numeroTarjeta) {
		this.numeroTarjeta = numeroTarjeta;
	}

	@Column(name = "cod_verificacion_tarjeta", unique = true, nullable = false, length = 3)
	public String getCodVerificacionTarjeta() {
		return this.codVerificacionTarjeta;
	}

	public void setCodVerificacionTarjeta(String codVerificacionTarjeta) {
		this.codVerificacionTarjeta = codVerificacionTarjeta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_deposito", nullable = false, length = 19)
	public Date getFechaDeposito() {
		return this.fechaDeposito;
	}

	public void setFechaDeposito(Date fechaDeposito) {
		this.fechaDeposito = fechaDeposito;
	}

	@Column(name = "monto_deposito", nullable = false, precision = 10)
	public BigDecimal getMontoDeposito() {
		return this.montoDeposito;
	}

	public void setMontoDeposito(BigDecimal montoDeposito) {
		this.montoDeposito = montoDeposito;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_vencimiento", nullable = false, length = 10)
	public Date getFechaVencimiento() {
		return this.fechaVencimiento;
	}

	public void setFechaVencimiento(Date fechaVencimiento) {
		this.fechaVencimiento = fechaVencimiento;
	}

	@Column(name = "nombre", length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tarjeta")
	public Set<Pago> getPagos() {
		return this.pagos;
	}

	public void setPagos(Set<Pago> pagos) {
		this.pagos = pagos;
	}

}
