package pe.edu.unsch.entities;
// Generated 19-nov-2020 18:08:16 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TransferenciaBancaria generated by hbm2java
 */
@Entity
@Table(name = "transferencia_bancaria", catalog = "marketplacebd_test")
public class TransferenciaBancaria implements java.io.Serializable {

	private int idtransferenciabancaria;
	private Pago pago;
	private String referenciaPago;
	private String direccionFacturacion;

	public TransferenciaBancaria() {
	}

	public TransferenciaBancaria(int idtransferenciabancaria, Pago pago) {
		this.idtransferenciabancaria = idtransferenciabancaria;
		this.pago = pago;
	}

	public TransferenciaBancaria(int idtransferenciabancaria, Pago pago, String referenciaPago,
			String direccionFacturacion) {
		this.idtransferenciabancaria = idtransferenciabancaria;
		this.pago = pago;
		this.referenciaPago = referenciaPago;
		this.direccionFacturacion = direccionFacturacion;
	}

	@Id

	@Column(name = "idtransferenciabancaria", unique = true, nullable = false)
	public int getIdtransferenciabancaria() {
		return this.idtransferenciabancaria;
	}

	public void setIdtransferenciabancaria(int idtransferenciabancaria) {
		this.idtransferenciabancaria = idtransferenciabancaria;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idpago", nullable = false)
	public Pago getPago() {
		return this.pago;
	}

	public void setPago(Pago pago) {
		this.pago = pago;
	}

	@Column(name = "referencia_pago", length = 45)
	public String getReferenciaPago() {
		return this.referenciaPago;
	}

	public void setReferenciaPago(String referenciaPago) {
		this.referenciaPago = referenciaPago;
	}

	@Column(name = "direccion_facturacion", length = 45)
	public String getDireccionFacturacion() {
		return this.direccionFacturacion;
	}

	public void setDireccionFacturacion(String direccionFacturacion) {
		this.direccionFacturacion = direccionFacturacion;
	}

}
