package pe.edu.unsch.entities;
// Generated 19-nov-2020 18:08:16 by Hibernate Tools 5.1.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", catalog = "marketplacebd_test", uniqueConstraints = @UniqueConstraint(columnNames = "usuario"))
public class Usuario implements java.io.Serializable {

	private Integer idusuario;
	private CompradorFrecuente compradorFrecuente;
	private String usuario;
	private String password;
	private Date ultimoLogin;
	private String historialDesUsuario;
	private Persona persona;
	private Integer idpersona;
	private Set<Comentario> comentarios = new HashSet<Comentario>(0);
	private Set<Carrito> carritos = new HashSet<Carrito>(0);
	private Set<ProductoDeseado> productoDeseados = new HashSet<ProductoDeseado>(0);
	private Set<RolUsuario> rolUsuarios = new HashSet<RolUsuario>(0);
	private Set<Reclamo> reclamos = new HashSet<Reclamo>(0);
	private Set<Pedido> pedidos = new HashSet<Pedido>(0);
	private Set<ProductoValorado> productoValorados = new HashSet<ProductoValorado>(0);

	public Usuario() {
	}

	public Usuario(String usuario, String password, String historialDesUsuario) {
		this.usuario = usuario;
		this.password = password;
		this.historialDesUsuario = historialDesUsuario;
	}

	public Usuario(CompradorFrecuente compradorFrecuente, String usuario, String password, Date ultimoLogin,
			String historialDesUsuario, Set<Comentario> comentarios, Set<Carrito> carritos,
			Set<ProductoDeseado> productoDeseados, Set<RolUsuario> rolUsuarios, Set<Reclamo> reclamos,
			Set<Pedido> pedidos, Set<ProductoValorado> productoValorados, Persona persona) {
		this.compradorFrecuente = compradorFrecuente;
		this.usuario = usuario;
		this.password = password;
		this.ultimoLogin = ultimoLogin;
		this.historialDesUsuario = historialDesUsuario;
		this.comentarios = comentarios;
		this.carritos = carritos;
		this.productoDeseados = productoDeseados;
		this.rolUsuarios = rolUsuarios;
		this.reclamos = reclamos;
		this.pedidos = pedidos;
		this.productoValorados = productoValorados;
		this.persona = persona;
	}

	public Usuario(String usuario, String password, Integer idusuario, Integer idpersona) {
		this.idusuario = idusuario;
		this.usuario = usuario;
		this.password = password;
		this.idpersona = idpersona;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idusuario", unique = true, nullable = false)
	public Integer getIdusuario() {
		return this.idusuario;
	}

	public void setIdusuario(Integer idusuario) {
		this.idusuario = idusuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcompradorfrecuente")
	public CompradorFrecuente getCompradorFrecuente() {
		return this.compradorFrecuente;
	}

	public void setCompradorFrecuente(CompradorFrecuente compradorFrecuente) {
		this.compradorFrecuente = compradorFrecuente;
	}

	@Column(name = "usuario", unique = true, nullable = false, length = 90)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Column(name = "password", nullable = false, length = 120)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ultimo_login", length = 19)
	public Date getUltimoLogin() {
		return this.ultimoLogin;
	}

	public void setUltimoLogin(Date ultimoLogin) {
		this.ultimoLogin = ultimoLogin;
	}

	@Column(name = "historial_des_usuario", nullable = false, length = 45)
	public String getHistorialDesUsuario() {
		return this.historialDesUsuario;
	}

	public void setHistorialDesUsuario(String historialDesUsuario) {
		this.historialDesUsuario = historialDesUsuario;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<Comentario> getComentarios() {
		return this.comentarios;
	}

	public void setComentarios(Set<Comentario> comentarios) {
		this.comentarios = comentarios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<Carrito> getCarritos() {
		return this.carritos;
	}

	public void setCarritos(Set<Carrito> carritos) {
		this.carritos = carritos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<ProductoDeseado> getProductoDeseados() {
		return this.productoDeseados;
	}

	public void setProductoDeseados(Set<ProductoDeseado> productoDeseados) {
		this.productoDeseados = productoDeseados;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<RolUsuario> getRolUsuarios() {
		return this.rolUsuarios;
	}

	public void setRolUsuarios(Set<RolUsuario> rolUsuarios) {
		this.rolUsuarios = rolUsuarios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<Reclamo> getReclamos() {
		return this.reclamos;
	}

	public void setReclamos(Set<Reclamo> reclamos) {
		this.reclamos = reclamos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<Pedido> getPedidos() {
		return this.pedidos;
	}

	public void setPedidos(Set<Pedido> pedidos) {
		this.pedidos = pedidos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<ProductoValorado> getProductoValorados() {
		return this.productoValorados;
	}

	public void setProductoValorados(Set<ProductoValorado> productoValorados) {
		this.productoValorados = productoValorados;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@Transient
	public Integer getIdpersona() {
		return idpersona;
	}

	public void setIdpersona(Integer idpersona) {
		this.idpersona = idpersona;
	}

}
