package pe.edu.unsch.entities;
// Generated 19-nov-2020 18:08:16 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VentaReporte generated by hbm2java
 */
@Entity
@Table(name = "venta_reporte", catalog = "marketplacebd_test")
public class VentaReporte implements java.io.Serializable {

	private Integer idventareporte;
	private Reporte reporte;
	private Venta venta;
	private String tipoReporte;

	public VentaReporte() {
	}

	public VentaReporte(Reporte reporte, Venta venta, String tipoReporte) {
		this.reporte = reporte;
		this.venta = venta;
		this.tipoReporte = tipoReporte;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idventareporte", unique = true, nullable = false)
	public Integer getIdventareporte() {
		return this.idventareporte;
	}

	public void setIdventareporte(Integer idventareporte) {
		this.idventareporte = idventareporte;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idreporte", nullable = false)
	public Reporte getReporte() {
		return this.reporte;
	}

	public void setReporte(Reporte reporte) {
		this.reporte = reporte;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idventa", nullable = false)
	public Venta getVenta() {
		return this.venta;
	}

	public void setVenta(Venta venta) {
		this.venta = venta;
	}

	@Column(name = "tipo_reporte", nullable = false, length = 80)
	public String getTipoReporte() {
		return this.tipoReporte;
	}

	public void setTipoReporte(String tipoReporte) {
		this.tipoReporte = tipoReporte;
	}

}
