package pe.edu.unsch.entities;
// Generated 19-nov-2020 18:08:16 by Hibernate Tools 5.1.10.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Venta generated by hbm2java
 */
@Entity
@Table(name = "venta", catalog = "marketplacebd_test")
public class Venta implements java.io.Serializable {

	private Integer idventa;
	private Pago pago;
	private Date fechaVenta;
	private BigDecimal monto;
	private Set<VentaReporte> ventaReportes = new HashSet<VentaReporte>(0);

	public Venta() {
	}

	public Venta(Pago pago, Date fechaVenta, BigDecimal monto) {
		this.pago = pago;
		this.fechaVenta = fechaVenta;
		this.monto = monto;
	}

	public Venta(Pago pago, Date fechaVenta, BigDecimal monto, Set<VentaReporte> ventaReportes) {
		this.pago = pago;
		this.fechaVenta = fechaVenta;
		this.monto = monto;
		this.ventaReportes = ventaReportes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idventa", unique = true, nullable = false)
	public Integer getIdventa() {
		return this.idventa;
	}

	public void setIdventa(Integer idventa) {
		this.idventa = idventa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idpago", nullable = false)
	public Pago getPago() {
		return this.pago;
	}

	public void setPago(Pago pago) {
		this.pago = pago;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_venta", nullable = false, length = 19)
	public Date getFechaVenta() {
		return this.fechaVenta;
	}

	public void setFechaVenta(Date fechaVenta) {
		this.fechaVenta = fechaVenta;
	}

	@Column(name = "monto", nullable = false, precision = 10)
	public BigDecimal getMonto() {
		return this.monto;
	}

	public void setMonto(BigDecimal monto) {
		this.monto = monto;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "venta")
	public Set<VentaReporte> getVentaReportes() {
		return this.ventaReportes;
	}

	public void setVentaReportes(Set<VentaReporte> ventaReportes) {
		this.ventaReportes = ventaReportes;
	}

}
